ktor:
    application:
        modules:
            - github.lukesovell.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://db:5432/default"
  user: test
  password: test